### ISSUE TITLE
Request & Response API

### ISSUE THREAD

**Issue by l1sss** [l1sss/http-server#4]
User should be able not to use OutputStream, also server must automatically set status line in response and handle possible exceptions in handlers.

Response should have following methods:

Response.setBody(byte[] data): void

Response.getWriter(): Writer

Reponse.getOutputStream(): OutputStream // but it should not send directly to client

Response.setHeader(String name, String value): void

Response.getHeaders(): Map<String, String>

Response.setHeaders(Map<String, String> headers): void

Response.setStatusCode(int code): void

Response.getStatusCode(): int

Support methods for most common headers:

Response.setContentLength(long length): void

Response.setContentType(String type): void

**Comment by SlimZik** [comment]
Done
